name: Build with analysis tools
on:
  workflow_dispatch:
    inputs:
      run_all_benchmarks:
        description: Run all benchmarks
        type: boolean
        default: false
      dev_image_tag:
        description: Tag of the ArcticDB development image to use for benchmark and code coverage flows
        type: string
        default: latest
      storage:
        description: Storage to run benchmarks against
        type: choice
        options:
        - LMDB
        - REAL
        - ALL
        default: LMDB
      suite_overwrite:
        description: Specify regular expression for specific tests to be executed
        type: string
        default: ''
      run_sanitizers:
        description: Run C++ tests with sanitizers enabled
        type: boolean
        default: false
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *
  pull_request:
    paths-ignore:
    - '**/*.md'
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
jobs:
  get_commits_to_benchmark:
    name: Get tag commits
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - name: Get tags
      id: get_tags
      run: |
        python3 build_tooling/get_commits_for_benchmark.py ${{ inputs.benchmark_all_tags == true && '--benchmark_all_tags' || ''}}
    outputs:
      matrix: ${{ steps.get_tags.outputs.commits }}
  benchmark_commits:
    needs:
    - get_commits_to_benchmark
    strategy:
      fail-fast: false
      matrix:
        commits: ${{ fromJson(needs.get_commits_to_benchmark.outputs.matrix)}}
    name: Benchmark commit ${{ matrix.commits }}
    uses: ./.github/workflows/benchmark_commits.yml
    secrets: inherit
    with:
      commit: ${{ matrix.commits }}
      benchmark_all_tags: ${{ inputs.benchmark_all_tags || false }}
      dev_image_tag: ${{ inputs.dev_image_tag || 'latest' }}
      storage: ${{  github.ref_name == 'master' && 'ALL' || inputs.storage || 'LMDB'}}
      suite_overwrite: ${{ inputs.suite_overwrite || ''}}
  publish_benchmark_results_to_gh_pages:
    name: Publish benchmark results to gh-pages
    if: ${{ github.event_name == 'schedule' }}
    needs:
    - benchmark_commits
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    permissions:
      contents: write
    steps:
    - name: Select Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'
    - name: Prepare environment
      shell: bash -el {0}
      run: |
        apt update
        apt install -y git
        python -m pip install arcticdb[Testing] "protobuf<6"
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - name: Publish results to Github Pages
      shell: bash -el {0}
      run: |
        python -m asv publish -v
        python -m asv gh-pages -v --rewrite
  run-asv-check-script:
    name: Executes asv tests checks
    timeout-minutes: 120
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        lfs: 'true'
        fetch-depth: 0
        submodules: recursive
    - name: Extra envs
      shell: bash -l {0}
      run: |
        . build_tooling/prep_cpp_build.sh
        . build_tooling/vcpkg_caching.sh
        cmake -P cpp/CMake/CpuCount.cmake | sed 's/^-- //' | tee -a $GITHUB_ENV
    - name: Build project for ASV
      run: |
        python -m pip install -ve .[Testing]
    - name: Run ASV Tests Check script
      run: |
        python python/utils/asv_checks.py
  sanitizer-address-leak-undefined:
    name: Tests with ASan+LSan+UBSan
    uses: ./.github/workflows/build_steps.yml
    secrets: inherit
    permissions:
      packages: write
    with:
      job_type: cpp-tests
      cmake_preset_type: debug
      matrix: '[{"os": "linux", "distro": "ubuntu-22.04", "container": {"image": "ghcr.io/man-group/arcticdb-dev-clang:latest"}, "cmake_preset_prefix": "linux", "cibw_build_suffix": "manylinux_x86_64", "build_dir": "/tmp/cpp_build_asan", "vcpkg_installed_dir": "/tmp/vcpkg_installed_asan", "vcpkg_packages_dir": "/tmp/vcpkg_packages_asan", "symbols": "*.pdb", "do_not_archive": ["*.o", "*.obj", "*.a", "*.lib"], "test_services": {}, "cmake_extra_args": "''-DARCTICDB_USING_ADDRESS_SANITIZER=ON'', ''-DARCTICDB_USING_UB_SANITIZER=ON''", "envs": "ARCTICDB_USE_SANITIZER=address,leak,undefined"}]'
